const std = @import("std");
const AccessFlags = @import("../Classfile/AccessFlags.zig");
const ClassFileModel = @import("../Classfile/ClassFileModel.zig");
const ConstantPoolBuilder = @import("../Classfile/ConstantPoolBuilder.zig");
const BytecodeInstructionModel = @import("../Classfile/BytecodeInstructionModel.zig");
const MaxStackLocalsComputer = @import("../Classfile/MaxStackLocalsComputer.zig");
const AssemblerModule = @import("../Classfile/Assembler.zig");

pub const Synthesized = struct { Bytes: []u8 };

const Assembler = AssemblerModule.AssemblerState;

fn BuildMethod(AllocatorHandle: std.mem.Allocator, Pool: *ConstantPoolBuilder.ConstantPool, Instructions: []BytecodeInstructionModel.Instruction, Descriptor: []const u8, IsStatic: bool, CodeUtf8Index: u16) !ClassFileModel.Attribute {
    var Code = BytecodeInstructionModel.CodeAttribute{ .MaxStack = 0, .MaxLocals = 0, .Instructions = .empty, .Exceptions = .empty, .Attributes = .empty, .NextIdentifier = 0 };
    Code.Instructions.items = Instructions;
    Code.Instructions.capacity = Instructions.len;
    var MaxNextIdentifier: u32 = 0;
    for (Instructions) |Instruction| {
        if (Instruction.Identifier + 1 > MaxNextIdentifier) MaxNextIdentifier = Instruction.Identifier + 1;
    }
    Code.NextIdentifier = MaxNextIdentifier;
    const MaxStackLocals = try MaxStackLocalsComputer.Compute(AllocatorHandle, Pool, &Code, Descriptor, IsStatic);
    Code.MaxStack = MaxStackLocals.MaxStack;
    Code.MaxLocals = MaxStackLocals.MaxLocals;
    try BytecodeInstructionModel.PrepareLayout(AllocatorHandle, &Code.Instructions);
    return .{ .NameIndex = CodeUtf8Index, .Info = try BytecodeInstructionModel.SerializeCode(AllocatorHandle, &Code) };
}

pub fn InterpreterClassSynthesizer(
    AllocatorHandle: std.mem.Allocator,
    InternalName: []const u8,
    ResourcePath: []const u8,
    NativeReaderInternal: []const u8,
    BinSeed: u32,
    Permutation: [64]u8,
    ExpectedHash: i64,
) !Synthesized {
    var Pool = try ConstantPoolBuilder.ConstantPool.InitEmpty(AllocatorHandle);
    const ThisClass = try Pool.AddClass(InternalName);
    const ObjectClass = try Pool.AddClass("java/lang/Object");
    const ObjectInit = try Pool.AddMethodref("java/lang/Object", "<init>", "()V");

    const ImageFieldName = try Pool.AddUtf8("I");
    const ImageFieldDescriptor = try Pool.AddUtf8("[B");
    const ImageFieldRef = try Pool.AddFieldref(InternalName, "I", "[B");

    const MapDescriptorUtf8 = try Pool.AddUtf8("Ljava/util/concurrent/ConcurrentHashMap;");
    const MethodCacheName = try Pool.AddUtf8("mC");
    const FieldCacheName = try Pool.AddUtf8("fC");
    const ConstructorCacheName = try Pool.AddUtf8("kC");
    const ClassCacheName = try Pool.AddUtf8("cC");
    const MethodCacheRef = try Pool.AddFieldref(InternalName, "mC", "Ljava/util/concurrent/ConcurrentHashMap;");
    const FieldCacheRef = try Pool.AddFieldref(InternalName, "fC", "Ljava/util/concurrent/ConcurrentHashMap;");
    const ConstructorCacheRef = try Pool.AddFieldref(InternalName, "kC", "Ljava/util/concurrent/ConcurrentHashMap;");
    const ClassCacheRef = try Pool.AddFieldref(InternalName, "cC", "Ljava/util/concurrent/ConcurrentHashMap;");
    const ConcurrentHashMapClass = try Pool.AddClass("java/util/concurrent/ConcurrentHashMap");
    const ConcurrentHashMapInit = try Pool.AddMethodref("java/util/concurrent/ConcurrentHashMap", "<init>", "()V");
    const MapGetRef = try Pool.AddMethodref("java/util/concurrent/ConcurrentHashMap", "get", "(Ljava/lang/Object;)Ljava/lang/Object;");
    const MapPutRef = try Pool.AddMethodref("java/util/concurrent/ConcurrentHashMap", "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
    const ReflectMethodClass = try Pool.AddClass("java/lang/reflect/Method");
    const ReflectFieldClass = try Pool.AddClass("java/lang/reflect/Field");
    const ReflectConstructorClass = try Pool.AddClass("java/lang/reflect/Constructor");
    const CachedForNameRef = try Pool.AddMethodref(InternalName, "cf", "(Ljava/lang/String;)Ljava/lang/Class;");

    const KeyByteMethodRef = try Pool.AddMethodref(NativeReaderInternal, "kb", "(II)I");
    const VerifyHashMethodRef = try Pool.AddMethodref(NativeReaderInternal, "vh", "([BJ)V");
    const ReadByteMethodRef = try Pool.AddMethodref(InternalName, "b", "(III)I");

    const GetResourceRef = try Pool.AddMethodref("java/lang/Class", "getResourceAsStream", "(Ljava/lang/String;)Ljava/io/InputStream;");
    const ReadAllBytesRef = try Pool.AddMethodref("java/io/InputStream", "readAllBytes", "()[B");
    const ResourceStringIndex = try Pool.AddString(ResourcePath);

    const StringClass = try Pool.AddClass("java/lang/String");
    const StringInitBytes = try Pool.AddMethodref("java/lang/String", "<init>", "([B)V");
    const LastIndexOfRef = try Pool.AddMethodref("java/lang/String", "lastIndexOf", "(I)I");
    const SubstringTwoArgRef = try Pool.AddMethodref("java/lang/String", "substring", "(II)Ljava/lang/String;");
    const SubstringOneArgRef = try Pool.AddMethodref("java/lang/String", "substring", "(I)Ljava/lang/String;");
    const ClassClass = try Pool.AddClass("java/lang/Class");
    const ForNameRef = try Pool.AddMethodref("java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;");
    const IntegerClass = try Pool.AddClass("java/lang/Integer");
    const IntegerTypeField = try Pool.AddFieldref("java/lang/Integer", "TYPE", "Ljava/lang/Class;");
    const ValueOfRef = try Pool.AddMethodref("java/lang/Integer", "valueOf", "(I)Ljava/lang/Integer;");
    const IntValueRef = try Pool.AddMethodref("java/lang/Integer", "intValue", "()I");
    const SetAccessibleRef = try Pool.AddMethodref("java/lang/reflect/AccessibleObject", "setAccessible", "(Z)V");
    const GetDeclaredFieldRef = try Pool.AddMethodref("java/lang/Class", "getField", "(Ljava/lang/String;)Ljava/lang/reflect/Field;");

    const LongClass = try Pool.AddClass("java/lang/Long");
    const LongValueOfRef = try Pool.AddMethodref("java/lang/Long", "valueOf", "(J)Ljava/lang/Long;");
    const LongLongValueRef = try Pool.AddMethodref("java/lang/Long", "longValue", "()J");
    const FloatClass = try Pool.AddClass("java/lang/Float");
    const FloatValueOfRef = try Pool.AddMethodref("java/lang/Float", "valueOf", "(F)Ljava/lang/Float;");
    const FloatFloatValueRef = try Pool.AddMethodref("java/lang/Float", "floatValue", "()F");
    const DoubleClass = try Pool.AddClass("java/lang/Double");
    const DoubleValueOfRef = try Pool.AddMethodref("java/lang/Double", "valueOf", "(D)Ljava/lang/Double;");
    const DoubleDoubleValueRef = try Pool.AddMethodref("java/lang/Double", "doubleValue", "()D");
    const NumberClass = try Pool.AddClass("java/lang/Number");
    const NumberIntValueRef = try Pool.AddMethodref("java/lang/Number", "intValue", "()I");
    const NumberLongValueRef = try Pool.AddMethodref("java/lang/Number", "longValue", "()J");
    const NumberFloatValueRef = try Pool.AddMethodref("java/lang/Number", "floatValue", "()F");
    const NumberDoubleValueRef = try Pool.AddMethodref("java/lang/Number", "doubleValue", "()D");

    const StringIndexOfRef = try Pool.AddMethodref("java/lang/String", "indexOf", "(I)I");
    const FromDescriptorRef = try Pool.AddMethodref("java/lang/invoke/MethodType", "fromMethodDescriptorString", "(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/lang/invoke/MethodType;");
    const ParameterArrayRef = try Pool.AddMethodref("java/lang/invoke/MethodType", "parameterArray", "()[Ljava/lang/Class;");
    const GetClassLoaderRef = try Pool.AddMethodref("java/lang/Class", "getClassLoader", "()Ljava/lang/ClassLoader;");
    const GetMethodRef = try Pool.AddMethodref("java/lang/Class", "getMethod", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;");
    const GetDeclaredConstructorRef = try Pool.AddMethodref("java/lang/Class", "getDeclaredConstructor", "([Ljava/lang/Class;)Ljava/lang/reflect/Constructor;");
    const NormalizeMethodRef = try Pool.AddMethodref(InternalName, "nz", "(Ljava/lang/Object;)Ljava/lang/Object;");
    const MethodParameterTypesRef = try Pool.AddMethodref("java/lang/reflect/Method", "getParameterTypes", "()[Ljava/lang/Class;");
    const GetDeclaredMethodsRef = try Pool.AddMethodref("java/lang/Class", "getDeclaredMethods", "()[Ljava/lang/reflect/Method;");
    const GetSuperclassRef = try Pool.AddMethodref("java/lang/Class", "getSuperclass", "()Ljava/lang/Class;");
    const MethodGetNameRef = try Pool.AddMethodref("java/lang/reflect/Method", "getName", "()Ljava/lang/String;");
    const StringEqualsRef = try Pool.AddMethodref("java/lang/String", "equals", "(Ljava/lang/Object;)Z");
    const ArraysEqualsRef = try Pool.AddMethodref("java/util/Arrays", "equals", "([Ljava/lang/Object;[Ljava/lang/Object;)Z");
    const ResolveDeclaredMethodRef = try Pool.AddMethodref(InternalName, "dm", "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;");
    const GetClassRef = try Pool.AddMethodref("java/lang/Object", "getClass", "()Ljava/lang/Class;");
    const MethodHandlesLookupRef = try Pool.AddMethodref("java/lang/invoke/MethodHandles", "lookup", "()Ljava/lang/invoke/MethodHandles$Lookup;");
    const PrivateLookupInRef = try Pool.AddMethodref("java/lang/invoke/MethodHandles", "privateLookupIn", "(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;");
    const UnreflectSpecialRef = try Pool.AddMethodref("java/lang/invoke/MethodHandles$Lookup", "unreflectSpecial", "(Ljava/lang/reflect/Method;Ljava/lang/Class;)Ljava/lang/invoke/MethodHandle;");
    const ArrayCopyRef = try Pool.AddMethodref("java/lang/System", "arraycopy", "(Ljava/lang/Object;ILjava/lang/Object;II)V");
    const InvokeWithArgumentsRef = try Pool.AddMethodref("java/lang/invoke/MethodHandle", "invokeWithArguments", "([Ljava/lang/Object;)Ljava/lang/Object;");
    const SpecialObjectArrayClass = try Pool.AddClass("java/lang/Object");
    const VmInitMethodRef = try Pool.AddMethodref(NativeReaderInternal, "vi", "([B[BLjava/lang/Class;)V");
    const BooleanClass = try Pool.AddClass("java/lang/Boolean");
    const BooleanValueOfRef = try Pool.AddMethodref("java/lang/Boolean", "valueOf", "(Z)Ljava/lang/Boolean;");
    const BooleanBooleanValueRef = try Pool.AddMethodref("java/lang/Boolean", "booleanValue", "()Z");
    const BooleanTypeField = try Pool.AddFieldref("java/lang/Boolean", "TYPE", "Ljava/lang/Class;");
    const ByteClass = try Pool.AddClass("java/lang/Byte");
    const ByteValueOfRef = try Pool.AddMethodref("java/lang/Byte", "valueOf", "(B)Ljava/lang/Byte;");
    const ByteTypeField = try Pool.AddFieldref("java/lang/Byte", "TYPE", "Ljava/lang/Class;");
    const CharacterClass = try Pool.AddClass("java/lang/Character");
    const CharacterValueOfRef = try Pool.AddMethodref("java/lang/Character", "valueOf", "(C)Ljava/lang/Character;");
    const CharacterCharValueRef = try Pool.AddMethodref("java/lang/Character", "charValue", "()C");
    const CharacterTypeField = try Pool.AddFieldref("java/lang/Character", "TYPE", "Ljava/lang/Class;");
    const ShortClass = try Pool.AddClass("java/lang/Short");
    const ShortValueOfRef = try Pool.AddMethodref("java/lang/Short", "valueOf", "(S)Ljava/lang/Short;");
    const ShortTypeField = try Pool.AddFieldref("java/lang/Short", "TYPE", "Ljava/lang/Class;");
    const LongTypeField = try Pool.AddFieldref("java/lang/Long", "TYPE", "Ljava/lang/Class;");
    const FloatTypeField = try Pool.AddFieldref("java/lang/Float", "TYPE", "Ljava/lang/Class;");
    const DoubleTypeField = try Pool.AddFieldref("java/lang/Double", "TYPE", "Ljava/lang/Class;");
    const ArrayGetRef = try Pool.AddMethodref("java/lang/reflect/Array", "get", "(Ljava/lang/Object;I)Ljava/lang/Object;");
    const ArraySetRef = try Pool.AddMethodref("java/lang/reflect/Array", "set", "(Ljava/lang/Object;ILjava/lang/Object;)V");
    const ArrayGetIntRef = try Pool.AddMethodref("java/lang/reflect/Array", "getInt", "(Ljava/lang/Object;I)I");
    const ArrayGetLongRef = try Pool.AddMethodref("java/lang/reflect/Array", "getLong", "(Ljava/lang/Object;I)J");
    const ArrayGetFloatRef = try Pool.AddMethodref("java/lang/reflect/Array", "getFloat", "(Ljava/lang/Object;I)F");
    const ArrayGetDoubleRef = try Pool.AddMethodref("java/lang/reflect/Array", "getDouble", "(Ljava/lang/Object;I)D");
    const ArrayGetCharRef = try Pool.AddMethodref("java/lang/reflect/Array", "getChar", "(Ljava/lang/Object;I)C");
    const ArrayGetShortRef = try Pool.AddMethodref("java/lang/reflect/Array", "getShort", "(Ljava/lang/Object;I)S");
    const ArraySetIntRef = try Pool.AddMethodref("java/lang/reflect/Array", "setInt", "(Ljava/lang/Object;II)V");
    const ArraySetLongRef = try Pool.AddMethodref("java/lang/reflect/Array", "setLong", "(Ljava/lang/Object;IJ)V");
    const ArraySetFloatRef = try Pool.AddMethodref("java/lang/reflect/Array", "setFloat", "(Ljava/lang/Object;IF)V");
    const ArraySetDoubleRef = try Pool.AddMethodref("java/lang/reflect/Array", "setDouble", "(Ljava/lang/Object;ID)V");
    const ArraySetCharRef = try Pool.AddMethodref("java/lang/reflect/Array", "setChar", "(Ljava/lang/Object;IC)V");
    const ArraySetShortRef = try Pool.AddMethodref("java/lang/reflect/Array", "setShort", "(Ljava/lang/Object;IS)V");
    const ArraySetBooleanRef = try Pool.AddMethodref("java/lang/reflect/Array", "setBoolean", "(Ljava/lang/Object;IZ)V");
    const ArraySetByteRef = try Pool.AddMethodref("java/lang/reflect/Array", "setByte", "(Ljava/lang/Object;IB)V");
    const BooleanArrayClass = try Pool.AddClass("[Z");
    const StringLengthRef = try Pool.AddMethodref("java/lang/String", "length", "()I");
    const StringCharAtRef = try Pool.AddMethodref("java/lang/String", "charAt", "(I)C");

    const CodeUtf8Index = try Pool.AddUtf8("Code");

    var InitAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try InitAssembler.Aload(0);
    try InitAssembler.Invoke(0xb7, ObjectInit);
    try InitAssembler.Operation0(0xb1);
    const InitMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try InitAssembler.Finish(), "()V", false, CodeUtf8Index);

    var ByteAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ByteAssembler.Invoke(0xb2, ImageFieldRef);
    try ByteAssembler.Iload(0);
    try ByteAssembler.Iload(2);
    try ByteAssembler.Operation0(0x60);
    try ByteAssembler.Operation0(0x33);
    try ByteAssembler.Iconst(255);
    try ByteAssembler.Operation0(0x7e);
    try ByteAssembler.Iload(2);
    try ByteAssembler.Iload(1);
    try ByteAssembler.Invoke(0xb8, KeyByteMethodRef);
    try ByteAssembler.Operation0(0x82);
    try ByteAssembler.Operation0(0xac);
    const ByteMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ByteAssembler.Finish(), "(III)I", true, CodeUtf8Index);

    const BinSeedConstant: i32 = @bitCast(BinSeed);
    var ClinitAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    for ([_]u16{ MethodCacheRef, FieldCacheRef, ConstructorCacheRef, ClassCacheRef }) |CacheFieldRef| {
        try ClinitAssembler.Operation2(0xbb, ConcurrentHashMapClass);
        try ClinitAssembler.Operation0(0x59);
        try ClinitAssembler.Invoke(0xb7, ConcurrentHashMapInit);
        try ClinitAssembler.Invoke(0xb3, CacheFieldRef);
    }
    try ClinitAssembler.Operation2(0x13, ThisClass);
    try ClinitAssembler.Operation2(0x13, ResourceStringIndex);
    try ClinitAssembler.Invoke(0xb6, GetResourceRef);
    try ClinitAssembler.Invoke(0xb6, ReadAllBytesRef);
    try ClinitAssembler.Astore(0);
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Operation2(0x14, try Pool.AddLong(ExpectedHash));
    try ClinitAssembler.Invoke(0xb8, VerifyHashMethodRef);
    try ClinitAssembler.Iconst(0);
    try ClinitAssembler.Istore(2);
    try ClinitAssembler.Label("dL");
    try ClinitAssembler.Iload(2);
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Operation0(0xbe);
    try ClinitAssembler.Branch(0xa2, "dD");
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Iload(2);
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Iload(2);
    try ClinitAssembler.Operation0(0x33);
    try ClinitAssembler.Iload(2);
    try ClinitAssembler.Iconst(BinSeedConstant);
    try ClinitAssembler.Invoke(0xb8, KeyByteMethodRef);
    try ClinitAssembler.Operation0(0x82);
    try ClinitAssembler.Operation0(0x91);
    try ClinitAssembler.Operation0(0x54);
    try ClinitAssembler.Iinc(2, 1);
    try ClinitAssembler.Goto("dL");
    try ClinitAssembler.Label("dD");
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Invoke(0xb3, ImageFieldRef);
    try ClinitAssembler.Aload(0);
    try ClinitAssembler.Iconst(64);
    try ClinitAssembler.Operation1(0xbc, 8);
    for (Permutation, 0..) |PermutationValue, PermutationIndex| {
        try ClinitAssembler.Operation0(0x59);
        try ClinitAssembler.Iconst(@intCast(PermutationIndex));
        try ClinitAssembler.Iconst(@as(i32, PermutationValue));
        try ClinitAssembler.Operation0(0x54);
    }
    try ClinitAssembler.Operation2(0x13, ThisClass);
    try ClinitAssembler.Invoke(0xb8, VmInitMethodRef);
    try ClinitAssembler.Operation0(0xb1);
    const ClinitMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ClinitAssembler.Finish(), "()V", true, CodeUtf8Index);

    var ReadFieldAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ReadFieldAssembler.Iload(3);
    try ReadFieldAssembler.Operation1(0xbc, 8);
    try ReadFieldAssembler.Astore(4);
    try ReadFieldAssembler.Iconst(0);
    try ReadFieldAssembler.Istore(5);
    try ReadFieldAssembler.Label("rL");
    try ReadFieldAssembler.Iload(5);
    try ReadFieldAssembler.Iload(3);
    try ReadFieldAssembler.Branch(0xa2, "rD");
    try ReadFieldAssembler.Aload(4);
    try ReadFieldAssembler.Iload(5);
    try ReadFieldAssembler.Iload(0);
    try ReadFieldAssembler.Iload(1);
    try ReadFieldAssembler.Iload(2);
    try ReadFieldAssembler.Iload(5);
    try ReadFieldAssembler.Operation0(0x60);
    try ReadFieldAssembler.Invoke(0xb8, ReadByteMethodRef);
    try ReadFieldAssembler.Operation0(0x91);
    try ReadFieldAssembler.Operation0(0x54);
    try ReadFieldAssembler.Iinc(5, 1);
    try ReadFieldAssembler.Goto("rL");
    try ReadFieldAssembler.Label("rD");
    try ReadFieldAssembler.Operation2(0xbb, StringClass);
    try ReadFieldAssembler.Operation0(0x59);
    try ReadFieldAssembler.Aload(4);
    try ReadFieldAssembler.Invoke(0xb7, StringInitBytes);
    try ReadFieldAssembler.Astore(6);
    try ReadFieldAssembler.Operation2(0xb2, FieldCacheRef);
    try ReadFieldAssembler.Aload(6);
    try ReadFieldAssembler.Invoke(0xb6, MapGetRef);
    try ReadFieldAssembler.Astore(9);
    try ReadFieldAssembler.Aload(9);
    try ReadFieldAssembler.Branch(0xc6, "rfMiss");
    try ReadFieldAssembler.Aload(9);
    try ReadFieldAssembler.Operation2(0xc0, ReflectFieldClass);
    try ReadFieldAssembler.Operation0(0xb0);
    try ReadFieldAssembler.Label("rfMiss");
    try ReadFieldAssembler.Aload(6);
    try ReadFieldAssembler.Iconst(46);
    try ReadFieldAssembler.Invoke(0xb6, LastIndexOfRef);
    try ReadFieldAssembler.Istore(7);
    try ReadFieldAssembler.Aload(6);
    try ReadFieldAssembler.Iconst(0);
    try ReadFieldAssembler.Iload(7);
    try ReadFieldAssembler.Invoke(0xb6, SubstringTwoArgRef);
    try ReadFieldAssembler.Invoke(0xb8, CachedForNameRef);
    try ReadFieldAssembler.Aload(6);
    try ReadFieldAssembler.Iload(7);
    try ReadFieldAssembler.Iconst(1);
    try ReadFieldAssembler.Operation0(0x60);
    try ReadFieldAssembler.Invoke(0xb6, SubstringOneArgRef);
    try ReadFieldAssembler.Invoke(0xb6, GetDeclaredFieldRef);
    try ReadFieldAssembler.Astore(8);
    try ReadFieldAssembler.Aload(8);
    try ReadFieldAssembler.Iconst(1);
    try ReadFieldAssembler.Invoke(0xb6, SetAccessibleRef);
    try ReadFieldAssembler.Operation2(0xb2, FieldCacheRef);
    try ReadFieldAssembler.Aload(6);
    try ReadFieldAssembler.Aload(8);
    try ReadFieldAssembler.Invoke(0xb6, MapPutRef);
    try ReadFieldAssembler.Operation0(0x57);
    try ReadFieldAssembler.Aload(8);
    try ReadFieldAssembler.Operation0(0xb0);
    const ReadFieldMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ReadFieldAssembler.Finish(), "(IIII)Ljava/lang/reflect/Field;", true, CodeUtf8Index);

    const WideReferences = WideRefs{ .LongClass = LongClass, .LongLongValue = LongLongValueRef, .IntegerClass = IntegerClass, .IntValue = IntValueRef };
    var ArithAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ArithAssembler.Aload(0);
    try ArithAssembler.Operation2(0xc1, LongClass);
    try ArithAssembler.Branch(0x99, "arnotlong");
    try ArithAssembler.Iload(2);
    var LongArithCaseNames = try AllocatorHandle.alloc([]const u8, 11);
    LongArithCaseNames[0] = "ladd";
    LongArithCaseNames[1] = "lsub";
    LongArithCaseNames[2] = "lmul";
    LongArithCaseNames[3] = "ldiv";
    LongArithCaseNames[4] = "lrem";
    LongArithCaseNames[5] = "land";
    LongArithCaseNames[6] = "lor";
    LongArithCaseNames[7] = "lxor";
    LongArithCaseNames[8] = "lshl";
    LongArithCaseNames[9] = "lshr";
    LongArithCaseNames[10] = "lushr";
    try ArithAssembler.TableSwitch(0, 10, "ladd", LongArithCaseNames);
    try LongArithCase(&ArithAssembler, "ladd", 0x61, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lsub", 0x65, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lmul", 0x69, false, WideReferences);
    try LongArithCase(&ArithAssembler, "ldiv", 0x6d, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lrem", 0x71, false, WideReferences);
    try LongArithCase(&ArithAssembler, "land", 0x7f, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lor", 0x81, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lxor", 0x83, false, WideReferences);
    try LongArithCase(&ArithAssembler, "lshl", 0x79, true, WideReferences);
    try LongArithCase(&ArithAssembler, "lshr", 0x7b, true, WideReferences);
    try LongArithCase(&ArithAssembler, "lushr", 0x7d, true, WideReferences);
    try ArithAssembler.Label("lbox");
    try ArithAssembler.Invoke(0xb8, LongValueOfRef);
    try ArithAssembler.Operation0(0xb0);
    try ArithAssembler.Label("arnotlong");
    try ArithAssembler.Aload(0);
    try ArithAssembler.Operation2(0xc1, FloatClass);
    try ArithAssembler.Branch(0x99, "arnotfloat");
    try ArithAssembler.Iload(2);
    var FloatArithCaseNames = try AllocatorHandle.alloc([]const u8, 5);
    FloatArithCaseNames[0] = "fadd";
    FloatArithCaseNames[1] = "fsub";
    FloatArithCaseNames[2] = "fmul";
    FloatArithCaseNames[3] = "fdiv";
    FloatArithCaseNames[4] = "frem";
    try ArithAssembler.TableSwitch(0, 4, "fadd", FloatArithCaseNames);
    try FloatDoubleArithCase(&ArithAssembler, "fadd", 0x62, FloatClass, FloatFloatValueRef, "fbox");
    try FloatDoubleArithCase(&ArithAssembler, "fsub", 0x66, FloatClass, FloatFloatValueRef, "fbox");
    try FloatDoubleArithCase(&ArithAssembler, "fmul", 0x6a, FloatClass, FloatFloatValueRef, "fbox");
    try FloatDoubleArithCase(&ArithAssembler, "fdiv", 0x6e, FloatClass, FloatFloatValueRef, "fbox");
    try FloatDoubleArithCase(&ArithAssembler, "frem", 0x72, FloatClass, FloatFloatValueRef, "fbox");
    try ArithAssembler.Label("fbox");
    try ArithAssembler.Invoke(0xb8, FloatValueOfRef);
    try ArithAssembler.Operation0(0xb0);
    try ArithAssembler.Label("arnotfloat");
    try ArithAssembler.Aload(0);
    try ArithAssembler.Operation2(0xc1, DoubleClass);
    try ArithAssembler.Branch(0x99, "arint");
    try ArithAssembler.Iload(2);
    var DoubleArithCaseNames = try AllocatorHandle.alloc([]const u8, 5);
    DoubleArithCaseNames[0] = "dadd";
    DoubleArithCaseNames[1] = "dsub";
    DoubleArithCaseNames[2] = "dmul";
    DoubleArithCaseNames[3] = "ddiv";
    DoubleArithCaseNames[4] = "drem";
    try ArithAssembler.TableSwitch(0, 4, "dadd", DoubleArithCaseNames);
    try FloatDoubleArithCase(&ArithAssembler, "dadd", 0x63, DoubleClass, DoubleDoubleValueRef, "dbox");
    try FloatDoubleArithCase(&ArithAssembler, "dsub", 0x67, DoubleClass, DoubleDoubleValueRef, "dbox");
    try FloatDoubleArithCase(&ArithAssembler, "dmul", 0x6b, DoubleClass, DoubleDoubleValueRef, "dbox");
    try FloatDoubleArithCase(&ArithAssembler, "ddiv", 0x6f, DoubleClass, DoubleDoubleValueRef, "dbox");
    try FloatDoubleArithCase(&ArithAssembler, "drem", 0x73, DoubleClass, DoubleDoubleValueRef, "dbox");
    try ArithAssembler.Label("dbox");
    try ArithAssembler.Invoke(0xb8, DoubleValueOfRef);
    try ArithAssembler.Operation0(0xb0);
    try ArithAssembler.Label("arint");
    try ArithAssembler.Aload(0);
    try ArithAssembler.Operation2(0xc0, IntegerClass);
    try ArithAssembler.Invoke(0xb6, IntValueRef);
    try ArithAssembler.Istore(3);
    try ArithAssembler.Aload(1);
    try ArithAssembler.Operation2(0xc0, IntegerClass);
    try ArithAssembler.Invoke(0xb6, IntValueRef);
    try ArithAssembler.Istore(4);
    try ArithAssembler.Iload(2);
    var ArithCaseNames = try AllocatorHandle.alloc([]const u8, 11);
    ArithCaseNames[0] = "oadd";
    ArithCaseNames[1] = "osub";
    ArithCaseNames[2] = "omul";
    ArithCaseNames[3] = "odiv";
    ArithCaseNames[4] = "orem";
    ArithCaseNames[5] = "oand";
    ArithCaseNames[6] = "oor";
    ArithCaseNames[7] = "oxor";
    ArithCaseNames[8] = "oshl";
    ArithCaseNames[9] = "oshr";
    ArithCaseNames[10] = "oushr";
    try ArithAssembler.TableSwitch(0, 10, "oadd", ArithCaseNames);
    try ArithCase(&ArithAssembler, "oadd", 0x60);
    try ArithCase(&ArithAssembler, "osub", 0x64);
    try ArithCase(&ArithAssembler, "omul", 0x68);
    try ArithCase(&ArithAssembler, "odiv", 0x6c);
    try ArithCase(&ArithAssembler, "orem", 0x70);
    try ArithCase(&ArithAssembler, "oand", 0x7e);
    try ArithCase(&ArithAssembler, "oor", 0x80);
    try ArithCase(&ArithAssembler, "oxor", 0x82);
    try ArithCase(&ArithAssembler, "oshl", 0x78);
    try ArithCase(&ArithAssembler, "oshr", 0x7a);
    try ArithCase(&ArithAssembler, "oushr", 0x7c);
    try ArithAssembler.Label("boxr");
    try ArithAssembler.Invoke(0xb8, ValueOfRef);
    try ArithAssembler.Operation0(0xb0);
    const ArithMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ArithAssembler.Finish(), "(Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;", true, CodeUtf8Index);

    var NegateAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc1, LongClass);
    try NegateAssembler.Branch(0x99, "ngnotlong");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc0, LongClass);
    try NegateAssembler.Invoke(0xb6, LongLongValueRef);
    try NegateAssembler.Operation0(0x75);
    try NegateAssembler.Invoke(0xb8, LongValueOfRef);
    try NegateAssembler.Operation0(0xb0);
    try NegateAssembler.Label("ngnotlong");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc1, FloatClass);
    try NegateAssembler.Branch(0x99, "ngnotfloat");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc0, FloatClass);
    try NegateAssembler.Invoke(0xb6, FloatFloatValueRef);
    try NegateAssembler.Operation0(0x76);
    try NegateAssembler.Invoke(0xb8, FloatValueOfRef);
    try NegateAssembler.Operation0(0xb0);
    try NegateAssembler.Label("ngnotfloat");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc1, DoubleClass);
    try NegateAssembler.Branch(0x99, "ngint");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc0, DoubleClass);
    try NegateAssembler.Invoke(0xb6, DoubleDoubleValueRef);
    try NegateAssembler.Operation0(0x77);
    try NegateAssembler.Invoke(0xb8, DoubleValueOfRef);
    try NegateAssembler.Operation0(0xb0);
    try NegateAssembler.Label("ngint");
    try NegateAssembler.Aload(0);
    try NegateAssembler.Operation2(0xc0, IntegerClass);
    try NegateAssembler.Invoke(0xb6, IntValueRef);
    try NegateAssembler.Operation0(0x74);
    try NegateAssembler.Invoke(0xb8, ValueOfRef);
    try NegateAssembler.Operation0(0xb0);
    const NegateMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try NegateAssembler.Finish(), "(Ljava/lang/Object;)Ljava/lang/Object;", true, CodeUtf8Index);

    var ConvertAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ConvertAssembler.Iload(1);
    var ConvertCaseNames = try AllocatorHandle.alloc([]const u8, 7);
    ConvertCaseNames[0] = "cvi";
    ConvertCaseNames[1] = "cvl";
    ConvertCaseNames[2] = "cvf";
    ConvertCaseNames[3] = "cvd";
    ConvertCaseNames[4] = "cvb";
    ConvertCaseNames[5] = "cvc";
    ConvertCaseNames[6] = "cvs";
    try ConvertAssembler.TableSwitch(0, 6, "cvdefault", ConvertCaseNames);
    try ConvertAssembler.Label("cvi");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberIntValueRef);
    try ConvertAssembler.Invoke(0xb8, ValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvl");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberLongValueRef);
    try ConvertAssembler.Invoke(0xb8, LongValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvb");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberIntValueRef);
    try ConvertAssembler.Operation0(0x91);
    try ConvertAssembler.Invoke(0xb8, ValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvc");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberIntValueRef);
    try ConvertAssembler.Operation0(0x92);
    try ConvertAssembler.Invoke(0xb8, ValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvs");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberIntValueRef);
    try ConvertAssembler.Operation0(0x93);
    try ConvertAssembler.Invoke(0xb8, ValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvf");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberFloatValueRef);
    try ConvertAssembler.Invoke(0xb8, FloatValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvd");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation2(0xc0, NumberClass);
    try ConvertAssembler.Invoke(0xb6, NumberDoubleValueRef);
    try ConvertAssembler.Invoke(0xb8, DoubleValueOfRef);
    try ConvertAssembler.Operation0(0xb0);
    try ConvertAssembler.Label("cvdefault");
    try ConvertAssembler.Aload(0);
    try ConvertAssembler.Operation0(0xb0);
    const ConvertMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ConvertAssembler.Finish(), "(Ljava/lang/Object;I)Ljava/lang/Object;", true, CodeUtf8Index);

    var CompareWideAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try CompareWideAssembler.Iload(2);
    var CompareWideCaseNames = try AllocatorHandle.alloc([]const u8, 5);
    CompareWideCaseNames[0] = "cwlcmp";
    CompareWideCaseNames[1] = "cwfcmpl";
    CompareWideCaseNames[2] = "cwfcmpg";
    CompareWideCaseNames[3] = "cwdcmpl";
    CompareWideCaseNames[4] = "cwdcmpg";
    try CompareWideAssembler.TableSwitch(0, 4, "cwdefault", CompareWideCaseNames);
    try CompareWideAssembler.Label("cwlcmp");
    try CompareWideAssembler.Aload(0);
    try CompareWideAssembler.Operation2(0xc0, LongClass);
    try CompareWideAssembler.Invoke(0xb6, LongLongValueRef);
    try CompareWideAssembler.Aload(1);
    try CompareWideAssembler.Operation2(0xc0, LongClass);
    try CompareWideAssembler.Invoke(0xb6, LongLongValueRef);
    try CompareWideAssembler.Operation0(0x94);
    try CompareWideAssembler.Invoke(0xb8, ValueOfRef);
    try CompareWideAssembler.Operation0(0xb0);
    try CompareWideCase(&CompareWideAssembler, "cwfcmpl", FloatClass, FloatFloatValueRef, 0x95, ValueOfRef);
    try CompareWideCase(&CompareWideAssembler, "cwfcmpg", FloatClass, FloatFloatValueRef, 0x96, ValueOfRef);
    try CompareWideCase(&CompareWideAssembler, "cwdcmpl", DoubleClass, DoubleDoubleValueRef, 0x97, ValueOfRef);
    try CompareWideCase(&CompareWideAssembler, "cwdcmpg", DoubleClass, DoubleDoubleValueRef, 0x98, ValueOfRef);
    try CompareWideAssembler.Label("cwdefault");
    try CompareWideAssembler.Iconst(0);
    try CompareWideAssembler.Invoke(0xb8, ValueOfRef);
    try CompareWideAssembler.Operation0(0xb0);
    const CompareWideMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try CompareWideAssembler.Finish(), "(Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;", true, CodeUtf8Index);

    var DeclaredMethodAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try DeclaredMethodAssembler.Aload(0);
    try DeclaredMethodAssembler.Astore(3);
    try DeclaredMethodAssembler.Label("dmClassLoop");
    try DeclaredMethodAssembler.Aload(3);
    try DeclaredMethodAssembler.Branch(0xc6, "dmFallback");
    try DeclaredMethodAssembler.Aload(3);
    try DeclaredMethodAssembler.Invoke(0xb6, GetDeclaredMethodsRef);
    try DeclaredMethodAssembler.Astore(4);
    try DeclaredMethodAssembler.Iconst(0);
    try DeclaredMethodAssembler.Istore(5);
    try DeclaredMethodAssembler.Label("dmMethodLoop");
    try DeclaredMethodAssembler.Iload(5);
    try DeclaredMethodAssembler.Aload(4);
    try DeclaredMethodAssembler.Operation0(0xbe);
    try DeclaredMethodAssembler.Branch(0xa2, "dmNextClass");
    try DeclaredMethodAssembler.Aload(4);
    try DeclaredMethodAssembler.Iload(5);
    try DeclaredMethodAssembler.Operation0(0x32);
    try DeclaredMethodAssembler.Astore(6);
    try DeclaredMethodAssembler.Aload(6);
    try DeclaredMethodAssembler.Invoke(0xb6, MethodGetNameRef);
    try DeclaredMethodAssembler.Aload(1);
    try DeclaredMethodAssembler.Invoke(0xb6, StringEqualsRef);
    try DeclaredMethodAssembler.Branch(0x99, "dmIncrement");
    try DeclaredMethodAssembler.Aload(6);
    try DeclaredMethodAssembler.Invoke(0xb6, MethodParameterTypesRef);
    try DeclaredMethodAssembler.Aload(2);
    try DeclaredMethodAssembler.Invoke(0xb8, ArraysEqualsRef);
    try DeclaredMethodAssembler.Branch(0x99, "dmIncrement");
    try DeclaredMethodAssembler.Aload(6);
    try DeclaredMethodAssembler.Operation0(0xb0);
    try DeclaredMethodAssembler.Label("dmIncrement");
    try DeclaredMethodAssembler.Iinc(5, 1);
    try DeclaredMethodAssembler.Goto("dmMethodLoop");
    try DeclaredMethodAssembler.Label("dmNextClass");
    try DeclaredMethodAssembler.Aload(3);
    try DeclaredMethodAssembler.Invoke(0xb6, GetSuperclassRef);
    try DeclaredMethodAssembler.Astore(3);
    try DeclaredMethodAssembler.Goto("dmClassLoop");
    try DeclaredMethodAssembler.Label("dmFallback");
    try DeclaredMethodAssembler.Aload(0);
    try DeclaredMethodAssembler.Aload(1);
    try DeclaredMethodAssembler.Aload(2);
    try DeclaredMethodAssembler.Invoke(0xb6, GetMethodRef);
    try DeclaredMethodAssembler.Operation0(0xb0);
    const DeclaredMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try DeclaredMethodAssembler.Finish(), "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", true, CodeUtf8Index);

    var ResolveCallAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ResolveCallAssembler.Operation2(0xb2, MethodCacheRef);
    try ResolveCallAssembler.Aload(0);
    try ResolveCallAssembler.Invoke(0xb6, MapGetRef);
    try ResolveCallAssembler.Astore(13);
    try ResolveCallAssembler.Aload(13);
    try ResolveCallAssembler.Branch(0xc6, "rcMiss");
    try ResolveCallAssembler.Aload(13);
    try ResolveCallAssembler.Operation2(0xc0, ReflectMethodClass);
    try ResolveCallAssembler.Operation0(0xb0);
    try ResolveCallAssembler.Label("rcMiss");
    try ResolveCallAssembler.Aload(0);
    try ResolveCallAssembler.Iconst(58);
    try ResolveCallAssembler.Invoke(0xb6, StringIndexOfRef);
    try ResolveCallAssembler.Istore(2);
    try ResolveCallAssembler.Aload(0);
    try ResolveCallAssembler.Iload(2);
    try ResolveCallAssembler.Iconst(1);
    try ResolveCallAssembler.Operation0(0x60);
    try ResolveCallAssembler.Invoke(0xb6, SubstringOneArgRef);
    try ResolveCallAssembler.Astore(3);
    try ResolveCallAssembler.Aload(0);
    try ResolveCallAssembler.Iconst(0);
    try ResolveCallAssembler.Iload(2);
    try ResolveCallAssembler.Invoke(0xb6, SubstringTwoArgRef);
    try ResolveCallAssembler.Astore(4);
    try ResolveCallAssembler.Aload(4);
    try ResolveCallAssembler.Iconst(46);
    try ResolveCallAssembler.Invoke(0xb6, LastIndexOfRef);
    try ResolveCallAssembler.Istore(5);
    try ResolveCallAssembler.Aload(4);
    try ResolveCallAssembler.Iconst(0);
    try ResolveCallAssembler.Iload(5);
    try ResolveCallAssembler.Invoke(0xb6, SubstringTwoArgRef);
    try ResolveCallAssembler.Astore(6);
    try ResolveCallAssembler.Aload(4);
    try ResolveCallAssembler.Iload(5);
    try ResolveCallAssembler.Iconst(1);
    try ResolveCallAssembler.Operation0(0x60);
    try ResolveCallAssembler.Invoke(0xb6, SubstringOneArgRef);
    try ResolveCallAssembler.Astore(7);
    try ResolveCallAssembler.Operation2(0x13, ThisClass);
    try ResolveCallAssembler.Invoke(0xb6, GetClassLoaderRef);
    try ResolveCallAssembler.Astore(8);
    try ResolveCallAssembler.Aload(3);
    try ResolveCallAssembler.Aload(8);
    try ResolveCallAssembler.Invoke(0xb8, FromDescriptorRef);
    try ResolveCallAssembler.Invoke(0xb6, ParameterArrayRef);
    try ResolveCallAssembler.Astore(10);
    try ResolveCallAssembler.Aload(6);
    try ResolveCallAssembler.Invoke(0xb8, CachedForNameRef);
    try ResolveCallAssembler.Astore(11);
    try ResolveCallAssembler.Iload(1);
    try ResolveCallAssembler.Iconst(1);
    try ResolveCallAssembler.Operation0(0x7e);
    try ResolveCallAssembler.Branch(0x99, "rcGetMethod");
    try ResolveCallAssembler.Aload(11);
    try ResolveCallAssembler.Aload(7);
    try ResolveCallAssembler.Aload(10);
    try ResolveCallAssembler.Invoke(0xb8, ResolveDeclaredMethodRef);
    try ResolveCallAssembler.Astore(12);
    try ResolveCallAssembler.Goto("rcHave");
    try ResolveCallAssembler.Label("rcGetMethod");
    try ResolveCallAssembler.Aload(11);
    try ResolveCallAssembler.Aload(7);
    try ResolveCallAssembler.Aload(10);
    try ResolveCallAssembler.Invoke(0xb6, GetMethodRef);
    try ResolveCallAssembler.Astore(12);
    try ResolveCallAssembler.Label("rcHave");
    try ResolveCallAssembler.Aload(12);
    try ResolveCallAssembler.Iconst(1);
    try ResolveCallAssembler.Invoke(0xb6, SetAccessibleRef);
    try ResolveCallAssembler.Operation2(0xb2, MethodCacheRef);
    try ResolveCallAssembler.Aload(0);
    try ResolveCallAssembler.Aload(12);
    try ResolveCallAssembler.Invoke(0xb6, MapPutRef);
    try ResolveCallAssembler.Operation0(0x57);
    try ResolveCallAssembler.Aload(12);
    try ResolveCallAssembler.Operation0(0xb0);
    const ResolveCallMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ResolveCallAssembler.Finish(), "(Ljava/lang/String;I)Ljava/lang/reflect/Method;", true, CodeUtf8Index);

    var SpecialAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try SpecialAssembler.Aload(1);
    try SpecialAssembler.Invoke(0xb6, GetClassRef);
    try SpecialAssembler.Astore(3);
    try SpecialAssembler.Aload(3);
    try SpecialAssembler.Invoke(0xb8, MethodHandlesLookupRef);
    try SpecialAssembler.Invoke(0xb8, PrivateLookupInRef);
    try SpecialAssembler.Astore(4);
    try SpecialAssembler.Aload(4);
    try SpecialAssembler.Aload(0);
    try SpecialAssembler.Aload(3);
    try SpecialAssembler.Invoke(0xb6, UnreflectSpecialRef);
    try SpecialAssembler.Astore(5);
    try SpecialAssembler.Aload(2);
    try SpecialAssembler.Operation0(0xbe);
    try SpecialAssembler.Iconst(1);
    try SpecialAssembler.Operation0(0x60);
    try SpecialAssembler.Operation2(0xbd, SpecialObjectArrayClass);
    try SpecialAssembler.Astore(6);
    try SpecialAssembler.Aload(6);
    try SpecialAssembler.Iconst(0);
    try SpecialAssembler.Aload(1);
    try SpecialAssembler.Operation0(0x53);
    try SpecialAssembler.Aload(2);
    try SpecialAssembler.Iconst(0);
    try SpecialAssembler.Aload(6);
    try SpecialAssembler.Iconst(1);
    try SpecialAssembler.Aload(2);
    try SpecialAssembler.Operation0(0xbe);
    try SpecialAssembler.Invoke(0xb8, ArrayCopyRef);
    try SpecialAssembler.Aload(5);
    try SpecialAssembler.Aload(6);
    try SpecialAssembler.Invoke(0xb6, InvokeWithArgumentsRef);
    try SpecialAssembler.Operation0(0xb0);
    const SpecialInvokeMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try SpecialAssembler.Finish(), "(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", true, CodeUtf8Index);

    var ResolveConstructorAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ResolveConstructorAssembler.Operation2(0xb2, ConstructorCacheRef);
    try ResolveConstructorAssembler.Aload(0);
    try ResolveConstructorAssembler.Invoke(0xb6, MapGetRef);
    try ResolveConstructorAssembler.Astore(9);
    try ResolveConstructorAssembler.Aload(9);
    try ResolveConstructorAssembler.Branch(0xc6, "rkMiss");
    try ResolveConstructorAssembler.Aload(9);
    try ResolveConstructorAssembler.Operation2(0xc0, ReflectConstructorClass);
    try ResolveConstructorAssembler.Operation0(0xb0);
    try ResolveConstructorAssembler.Label("rkMiss");
    try ResolveConstructorAssembler.Aload(0);
    try ResolveConstructorAssembler.Iconst(58);
    try ResolveConstructorAssembler.Invoke(0xb6, StringIndexOfRef);
    try ResolveConstructorAssembler.Istore(1);
    try ResolveConstructorAssembler.Aload(0);
    try ResolveConstructorAssembler.Iconst(0);
    try ResolveConstructorAssembler.Iload(1);
    try ResolveConstructorAssembler.Invoke(0xb6, SubstringTwoArgRef);
    try ResolveConstructorAssembler.Astore(2);
    try ResolveConstructorAssembler.Aload(0);
    try ResolveConstructorAssembler.Iload(1);
    try ResolveConstructorAssembler.Iconst(1);
    try ResolveConstructorAssembler.Operation0(0x60);
    try ResolveConstructorAssembler.Invoke(0xb6, SubstringOneArgRef);
    try ResolveConstructorAssembler.Astore(3);
    try ResolveConstructorAssembler.Operation2(0x13, ThisClass);
    try ResolveConstructorAssembler.Invoke(0xb6, GetClassLoaderRef);
    try ResolveConstructorAssembler.Astore(4);
    try ResolveConstructorAssembler.Aload(3);
    try ResolveConstructorAssembler.Aload(4);
    try ResolveConstructorAssembler.Invoke(0xb8, FromDescriptorRef);
    try ResolveConstructorAssembler.Invoke(0xb6, ParameterArrayRef);
    try ResolveConstructorAssembler.Astore(6);
    try ResolveConstructorAssembler.Aload(2);
    try ResolveConstructorAssembler.Invoke(0xb8, CachedForNameRef);
    try ResolveConstructorAssembler.Aload(6);
    try ResolveConstructorAssembler.Invoke(0xb6, GetDeclaredConstructorRef);
    try ResolveConstructorAssembler.Astore(8);
    try ResolveConstructorAssembler.Aload(8);
    try ResolveConstructorAssembler.Iconst(1);
    try ResolveConstructorAssembler.Invoke(0xb6, SetAccessibleRef);
    try ResolveConstructorAssembler.Operation2(0xb2, ConstructorCacheRef);
    try ResolveConstructorAssembler.Aload(0);
    try ResolveConstructorAssembler.Aload(8);
    try ResolveConstructorAssembler.Invoke(0xb6, MapPutRef);
    try ResolveConstructorAssembler.Operation0(0x57);
    try ResolveConstructorAssembler.Aload(8);
    try ResolveConstructorAssembler.Operation0(0xb0);
    const ResolveConstructorMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ResolveConstructorAssembler.Finish(), "(Ljava/lang/String;)Ljava/lang/reflect/Constructor;", true, CodeUtf8Index);

    var NormalizeAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc1, BooleanClass);
    try NormalizeAssembler.Branch(0x99, "nzNotBool");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc0, BooleanClass);
    try NormalizeAssembler.Invoke(0xb6, BooleanBooleanValueRef);
    try NormalizeAssembler.Invoke(0xb8, ValueOfRef);
    try NormalizeAssembler.Operation0(0xb0);
    try NormalizeAssembler.Label("nzNotBool");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc1, ByteClass);
    try NormalizeAssembler.Branch(0x99, "nzNotByte");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc0, NumberClass);
    try NormalizeAssembler.Invoke(0xb6, NumberIntValueRef);
    try NormalizeAssembler.Invoke(0xb8, ValueOfRef);
    try NormalizeAssembler.Operation0(0xb0);
    try NormalizeAssembler.Label("nzNotByte");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc1, CharacterClass);
    try NormalizeAssembler.Branch(0x99, "nzNotChar");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc0, CharacterClass);
    try NormalizeAssembler.Invoke(0xb6, CharacterCharValueRef);
    try NormalizeAssembler.Invoke(0xb8, ValueOfRef);
    try NormalizeAssembler.Operation0(0xb0);
    try NormalizeAssembler.Label("nzNotChar");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc1, ShortClass);
    try NormalizeAssembler.Branch(0x99, "nzNotShort");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation2(0xc0, NumberClass);
    try NormalizeAssembler.Invoke(0xb6, NumberIntValueRef);
    try NormalizeAssembler.Invoke(0xb8, ValueOfRef);
    try NormalizeAssembler.Operation0(0xb0);
    try NormalizeAssembler.Label("nzNotShort");
    try NormalizeAssembler.Aload(0);
    try NormalizeAssembler.Operation0(0xb0);
    const NormalizeMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try NormalizeAssembler.Finish(), "(Ljava/lang/Object;)Ljava/lang/Object;", true, CodeUtf8Index);

    var CoerceAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try CoerceAssembler.Aload(0);
    try CoerceAssembler.Operation2(0xc1, IntegerClass);
    try CoerceAssembler.Branch(0x9a, "coIsInt");
    try CoerceAssembler.Aload(0);
    try CoerceAssembler.Operation0(0xb0);
    try CoerceAssembler.Label("coIsInt");
    try CoerceAssembler.Aload(0);
    try CoerceAssembler.Operation2(0xc0, IntegerClass);
    try CoerceAssembler.Invoke(0xb6, IntValueRef);
    try CoerceAssembler.Istore(2);
    try CoerceAssembler.Aload(1);
    try CoerceAssembler.Operation2(0xb2, BooleanTypeField);
    try CoerceAssembler.Branch(0xa6, "coNotBool");
    try CoerceAssembler.Iload(2);
    try CoerceAssembler.Branch(0x99, "coBoolFalse");
    try CoerceAssembler.Iconst(1);
    try CoerceAssembler.Goto("coBoolSet");
    try CoerceAssembler.Label("coBoolFalse");
    try CoerceAssembler.Iconst(0);
    try CoerceAssembler.Label("coBoolSet");
    try CoerceAssembler.Invoke(0xb8, BooleanValueOfRef);
    try CoerceAssembler.Operation0(0xb0);
    try CoerceAssembler.Label("coNotBool");
    try CoerceAssembler.Aload(1);
    try CoerceAssembler.Operation2(0xb2, ByteTypeField);
    try CoerceAssembler.Branch(0xa6, "coNotByte");
    try CoerceAssembler.Iload(2);
    try CoerceAssembler.Operation0(0x91);
    try CoerceAssembler.Invoke(0xb8, ByteValueOfRef);
    try CoerceAssembler.Operation0(0xb0);
    try CoerceAssembler.Label("coNotByte");
    try CoerceAssembler.Aload(1);
    try CoerceAssembler.Operation2(0xb2, CharacterTypeField);
    try CoerceAssembler.Branch(0xa6, "coNotChar");
    try CoerceAssembler.Iload(2);
    try CoerceAssembler.Operation0(0x92);
    try CoerceAssembler.Invoke(0xb8, CharacterValueOfRef);
    try CoerceAssembler.Operation0(0xb0);
    try CoerceAssembler.Label("coNotChar");
    try CoerceAssembler.Aload(1);
    try CoerceAssembler.Operation2(0xb2, ShortTypeField);
    try CoerceAssembler.Branch(0xa6, "coNotShort");
    try CoerceAssembler.Iload(2);
    try CoerceAssembler.Operation0(0x93);
    try CoerceAssembler.Invoke(0xb8, ShortValueOfRef);
    try CoerceAssembler.Operation0(0xb0);
    try CoerceAssembler.Label("coNotShort");
    try CoerceAssembler.Aload(0);
    try CoerceAssembler.Operation0(0xb0);
    const CoerceMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try CoerceAssembler.Finish(), "(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;", true, CodeUtf8Index);

    var ArrayTypeAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ArrayTypeAssembler.Iload(0);
    var ArrayTypeCaseNames = try AllocatorHandle.alloc([]const u8, 8);
    ArrayTypeCaseNames[0] = "atBool";
    ArrayTypeCaseNames[1] = "atChar";
    ArrayTypeCaseNames[2] = "atFloat";
    ArrayTypeCaseNames[3] = "atDouble";
    ArrayTypeCaseNames[4] = "atByte";
    ArrayTypeCaseNames[5] = "atShort";
    ArrayTypeCaseNames[6] = "atInt";
    ArrayTypeCaseNames[7] = "atLong";
    try ArrayTypeAssembler.TableSwitch(4, 11, "atInt", ArrayTypeCaseNames);
    try EmitTypeCase(&ArrayTypeAssembler, "atBool", BooleanTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atChar", CharacterTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atFloat", FloatTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atDouble", DoubleTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atByte", ByteTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atShort", ShortTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atInt", IntegerTypeField);
    try EmitTypeCase(&ArrayTypeAssembler, "atLong", LongTypeField);
    const ArrayTypeMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ArrayTypeAssembler.Finish(), "(I)Ljava/lang/Class;", true, CodeUtf8Index);

    var ArrayLoadAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ArrayLoadAssembler.Iload(2);
    var ArrayLoadCaseNames = try AllocatorHandle.alloc([]const u8, 8);
    ArrayLoadCaseNames[0] = "alI";
    ArrayLoadCaseNames[1] = "alL";
    ArrayLoadCaseNames[2] = "alF";
    ArrayLoadCaseNames[3] = "alD";
    ArrayLoadCaseNames[4] = "alA";
    ArrayLoadCaseNames[5] = "alB";
    ArrayLoadCaseNames[6] = "alC";
    ArrayLoadCaseNames[7] = "alS";
    try ArrayLoadAssembler.TableSwitch(0, 7, "alA", ArrayLoadCaseNames);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alI", ArrayGetIntRef, ValueOfRef);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alL", ArrayGetLongRef, LongValueOfRef);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alF", ArrayGetFloatRef, FloatValueOfRef);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alD", ArrayGetDoubleRef, DoubleValueOfRef);
    try ArrayLoadAssembler.Label("alA");
    try ArrayLoadAssembler.Aload(0);
    try ArrayLoadAssembler.Iload(1);
    try ArrayLoadAssembler.Invoke(0xb8, ArrayGetRef);
    try ArrayLoadAssembler.Operation0(0xb0);
    try ArrayLoadAssembler.Label("alB");
    try ArrayLoadAssembler.Aload(0);
    try ArrayLoadAssembler.Iload(1);
    try ArrayLoadAssembler.Invoke(0xb8, ArrayGetRef);
    try ArrayLoadAssembler.Invoke(0xb8, NormalizeMethodRef);
    try ArrayLoadAssembler.Operation0(0xb0);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alC", ArrayGetCharRef, ValueOfRef);
    try EmitArrayLoadCase(&ArrayLoadAssembler, "alS", ArrayGetShortRef, ValueOfRef);
    const ArrayLoadMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ArrayLoadAssembler.Finish(), "(Ljava/lang/Object;II)Ljava/lang/Object;", true, CodeUtf8Index);

    var ArrayStoreAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try ArrayStoreAssembler.Iload(3);
    var ArrayStoreCaseNames = try AllocatorHandle.alloc([]const u8, 8);
    ArrayStoreCaseNames[0] = "asI";
    ArrayStoreCaseNames[1] = "asL";
    ArrayStoreCaseNames[2] = "asF";
    ArrayStoreCaseNames[3] = "asD";
    ArrayStoreCaseNames[4] = "asA";
    ArrayStoreCaseNames[5] = "asB";
    ArrayStoreCaseNames[6] = "asC";
    ArrayStoreCaseNames[7] = "asS";
    try ArrayStoreAssembler.TableSwitch(0, 7, "asA", ArrayStoreCaseNames);
    try EmitArrayStoreWide(&ArrayStoreAssembler, "asI", IntegerClass, IntValueRef, ArraySetIntRef);
    try EmitArrayStoreWide(&ArrayStoreAssembler, "asL", LongClass, LongLongValueRef, ArraySetLongRef);
    try EmitArrayStoreWide(&ArrayStoreAssembler, "asF", FloatClass, FloatFloatValueRef, ArraySetFloatRef);
    try EmitArrayStoreWide(&ArrayStoreAssembler, "asD", DoubleClass, DoubleDoubleValueRef, ArraySetDoubleRef);
    try ArrayStoreAssembler.Label("asA");
    try ArrayStoreAssembler.Aload(0);
    try ArrayStoreAssembler.Iload(1);
    try ArrayStoreAssembler.Aload(2);
    try ArrayStoreAssembler.Invoke(0xb8, ArraySetRef);
    try ArrayStoreAssembler.Operation0(0xb1);
    try ArrayStoreAssembler.Label("asB");
    try ArrayStoreAssembler.Aload(0);
    try ArrayStoreAssembler.Operation2(0xc1, BooleanArrayClass);
    try ArrayStoreAssembler.Branch(0x99, "asByteArr");
    try ArrayStoreAssembler.Aload(0);
    try ArrayStoreAssembler.Iload(1);
    try ArrayStoreAssembler.Aload(2);
    try ArrayStoreAssembler.Operation2(0xc0, IntegerClass);
    try ArrayStoreAssembler.Invoke(0xb6, IntValueRef);
    try ArrayStoreAssembler.Branch(0x99, "asBoolFalse");
    try ArrayStoreAssembler.Iconst(1);
    try ArrayStoreAssembler.Goto("asBoolSet");
    try ArrayStoreAssembler.Label("asBoolFalse");
    try ArrayStoreAssembler.Iconst(0);
    try ArrayStoreAssembler.Label("asBoolSet");
    try ArrayStoreAssembler.Invoke(0xb8, ArraySetBooleanRef);
    try ArrayStoreAssembler.Operation0(0xb1);
    try ArrayStoreAssembler.Label("asByteArr");
    try ArrayStoreAssembler.Aload(0);
    try ArrayStoreAssembler.Iload(1);
    try ArrayStoreAssembler.Aload(2);
    try ArrayStoreAssembler.Operation2(0xc0, IntegerClass);
    try ArrayStoreAssembler.Invoke(0xb6, IntValueRef);
    try ArrayStoreAssembler.Operation0(0x91);
    try ArrayStoreAssembler.Invoke(0xb8, ArraySetByteRef);
    try ArrayStoreAssembler.Operation0(0xb1);
    try EmitArrayStoreNarrow(&ArrayStoreAssembler, "asC", IntegerClass, IntValueRef, 0x92, ArraySetCharRef);
    try EmitArrayStoreNarrow(&ArrayStoreAssembler, "asS", IntegerClass, IntValueRef, 0x93, ArraySetShortRef);
    const ArrayStoreMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try ArrayStoreAssembler.Finish(), "(Ljava/lang/Object;ILjava/lang/Object;I)V", true, CodeUtf8Index);

    var MultiComponentAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Invoke(0xb6, StringLengthRef);
    try MultiComponentAssembler.Iconst(1);
    try MultiComponentAssembler.Branch(0xa0, "mcRef");
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Iconst(0);
    try MultiComponentAssembler.Invoke(0xb6, StringCharAtRef);
    try MultiComponentAssembler.Istore(1);
    try EmitMcPrimCase(&MultiComponentAssembler, 73, IntegerTypeField, "mcN1");
    try EmitMcPrimCase(&MultiComponentAssembler, 74, LongTypeField, "mcN2");
    try EmitMcPrimCase(&MultiComponentAssembler, 70, FloatTypeField, "mcN3");
    try EmitMcPrimCase(&MultiComponentAssembler, 68, DoubleTypeField, "mcN4");
    try EmitMcPrimCase(&MultiComponentAssembler, 90, BooleanTypeField, "mcN5");
    try EmitMcPrimCase(&MultiComponentAssembler, 66, ByteTypeField, "mcN6");
    try EmitMcPrimCase(&MultiComponentAssembler, 67, CharacterTypeField, "mcN7");
    try EmitMcPrimCase(&MultiComponentAssembler, 83, ShortTypeField, "mcRef");
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Iconst(0);
    try MultiComponentAssembler.Invoke(0xb6, StringCharAtRef);
    try MultiComponentAssembler.Iconst(76);
    try MultiComponentAssembler.Branch(0xa0, "mcArr");
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Iconst(1);
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Invoke(0xb6, StringLengthRef);
    try MultiComponentAssembler.Iconst(1);
    try MultiComponentAssembler.Operation0(0x64);
    try MultiComponentAssembler.Invoke(0xb6, SubstringTwoArgRef);
    try MultiComponentAssembler.Invoke(0xb8, ForNameRef);
    try MultiComponentAssembler.Operation0(0xb0);
    try MultiComponentAssembler.Label("mcArr");
    try MultiComponentAssembler.Aload(0);
    try MultiComponentAssembler.Invoke(0xb8, ForNameRef);
    try MultiComponentAssembler.Operation0(0xb0);
    const MultiComponentMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try MultiComponentAssembler.Finish(), "(Ljava/lang/String;)Ljava/lang/Class;", true, CodeUtf8Index);

    var CachedForNameAssembler = Assembler.Initialize(AllocatorHandle, &Pool);
    try CachedForNameAssembler.Operation2(0xb2, ClassCacheRef);
    try CachedForNameAssembler.Aload(0);
    try CachedForNameAssembler.Invoke(0xb6, MapGetRef);
    try CachedForNameAssembler.Astore(1);
    try CachedForNameAssembler.Aload(1);
    try CachedForNameAssembler.Branch(0xc6, "cfResolve");
    try CachedForNameAssembler.Aload(1);
    try CachedForNameAssembler.Operation2(0xc0, ClassClass);
    try CachedForNameAssembler.Operation0(0xb0);
    try CachedForNameAssembler.Label("cfResolve");
    try CachedForNameAssembler.Aload(0);
    try CachedForNameAssembler.Invoke(0xb8, ForNameRef);
    try CachedForNameAssembler.Astore(1);
    try CachedForNameAssembler.Operation2(0xb2, ClassCacheRef);
    try CachedForNameAssembler.Aload(0);
    try CachedForNameAssembler.Aload(1);
    try CachedForNameAssembler.Invoke(0xb6, MapPutRef);
    try CachedForNameAssembler.Operation0(0x57);
    try CachedForNameAssembler.Aload(1);
    try CachedForNameAssembler.Operation0(0xb0);
    const CachedForNameMethodInfo = try BuildMethod(AllocatorHandle, &Pool, try CachedForNameAssembler.Finish(), "(Ljava/lang/String;)Ljava/lang/Class;", true, CodeUtf8Index);

    var Fields: std.ArrayList(ClassFileModel.MemberInfo) = .empty;
    try Fields.append(AllocatorHandle, .{ .AccessFlags = AccessFlags.AccessStatic | AccessFlags.AccessPrivate, .NameIndex = ImageFieldName, .DescriptorIndex = ImageFieldDescriptor, .Attributes = .empty });
    try Fields.append(AllocatorHandle, .{ .AccessFlags = AccessFlags.AccessStatic | AccessFlags.AccessPrivate, .NameIndex = MethodCacheName, .DescriptorIndex = MapDescriptorUtf8, .Attributes = .empty });
    try Fields.append(AllocatorHandle, .{ .AccessFlags = AccessFlags.AccessStatic | AccessFlags.AccessPrivate, .NameIndex = FieldCacheName, .DescriptorIndex = MapDescriptorUtf8, .Attributes = .empty });
    try Fields.append(AllocatorHandle, .{ .AccessFlags = AccessFlags.AccessStatic | AccessFlags.AccessPrivate, .NameIndex = ConstructorCacheName, .DescriptorIndex = MapDescriptorUtf8, .Attributes = .empty });
    try Fields.append(AllocatorHandle, .{ .AccessFlags = AccessFlags.AccessStatic | AccessFlags.AccessPrivate, .NameIndex = ClassCacheName, .DescriptorIndex = MapDescriptorUtf8, .Attributes = .empty });

    var Methods: std.ArrayList(ClassFileModel.MemberInfo) = .empty;
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessPublic, "<init>", "()V", InitMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic, "<clinit>", "()V", ClinitMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "b", "(III)I", ByteMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "rf", "(IIII)Ljava/lang/reflect/Field;", ReadFieldMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "ar", "(Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;", ArithMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "ng", "(Ljava/lang/Object;)Ljava/lang/Object;", NegateMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "cv", "(Ljava/lang/Object;I)Ljava/lang/Object;", ConvertMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "cw", "(Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;", CompareWideMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "rc", "(Ljava/lang/String;I)Ljava/lang/reflect/Method;", ResolveCallMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "sp", "(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", SpecialInvokeMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "dm", "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", DeclaredMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "rk", "(Ljava/lang/String;)Ljava/lang/reflect/Constructor;", ResolveConstructorMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "nz", "(Ljava/lang/Object;)Ljava/lang/Object;", NormalizeMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "co", "(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;", CoerceMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "at", "(I)Ljava/lang/Class;", ArrayTypeMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "al", "(Ljava/lang/Object;II)Ljava/lang/Object;", ArrayLoadMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "as", "(Ljava/lang/Object;ILjava/lang/Object;I)V", ArrayStoreMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "mc", "(Ljava/lang/String;)Ljava/lang/Class;", MultiComponentMethodInfo);
    try AddMethod(AllocatorHandle, &Methods, &Pool, AccessFlags.AccessStatic | AccessFlags.AccessPrivate, "cf", "(Ljava/lang/String;)Ljava/lang/Class;", CachedForNameMethodInfo);

    var ClassFileValue = ClassFileModel.ClassFile{
        .Allocator = AllocatorHandle,
        .Minor = 0,
        .Major = MajorVersion,
        .ConstantPool = Pool,
        .AccessFlags = AccessFlags.AccessPublic | AccessFlags.AccessFinal | AccessFlags.AccessSuper,
        .ThisClass = ThisClass,
        .SuperClass = ObjectClass,
        .Interfaces = .empty,
        .Fields = Fields,
        .Methods = Methods,
        .Attributes = .empty,
    };
    return .{ .Bytes = try ClassFileModel.Serialize(AllocatorHandle, &ClassFileValue) };
}

const MajorVersion: u16 = 49;

fn AddMethod(AllocatorHandle: std.mem.Allocator, Methods: *std.ArrayList(ClassFileModel.MemberInfo), Pool: *ConstantPoolBuilder.ConstantPool, Flags: u16, Name: []const u8, Descriptor: []const u8, CodeInfo: ClassFileModel.Attribute) !void {
    var Attributes: std.ArrayList(ClassFileModel.Attribute) = .empty;
    try Attributes.append(AllocatorHandle, CodeInfo);
    try Methods.append(AllocatorHandle, .{ .AccessFlags = Flags, .NameIndex = try Pool.AddUtf8(Name), .DescriptorIndex = try Pool.AddUtf8(Descriptor), .Attributes = Attributes });
}

fn ArithCase(AssemblerHandle: *Assembler, Name: []const u8, ArithmeticOpcode: u8) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Iload(3);
    try AssemblerHandle.Iload(4);
    try AssemblerHandle.Operation0(ArithmeticOpcode);
    try AssemblerHandle.Goto("boxr");
}

const WideRefs = struct { LongClass: u16, LongLongValue: u16, IntegerClass: u16, IntValue: u16 };

fn LongArithCase(AssemblerHandle: *Assembler, Name: []const u8, ArithmeticOpcode: u8, ShiftCountIsInt: bool, Refs: WideRefs) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Operation2(0xc0, Refs.LongClass);
    try AssemblerHandle.Invoke(0xb6, Refs.LongLongValue);
    if (ShiftCountIsInt) {
        try AssemblerHandle.Aload(1);
        try AssemblerHandle.Operation2(0xc0, Refs.IntegerClass);
        try AssemblerHandle.Invoke(0xb6, Refs.IntValue);
    } else {
        try AssemblerHandle.Aload(1);
        try AssemblerHandle.Operation2(0xc0, Refs.LongClass);
        try AssemblerHandle.Invoke(0xb6, Refs.LongLongValue);
    }
    try AssemblerHandle.Operation0(ArithmeticOpcode);
    try AssemblerHandle.Goto("lbox");
}

fn FloatDoubleArithCase(AssemblerHandle: *Assembler, Name: []const u8, ArithmeticOpcode: u8, ValueClass: u16, ValueMethod: u16, BoxLabel: []const u8) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Operation2(0xc0, ValueClass);
    try AssemblerHandle.Invoke(0xb6, ValueMethod);
    try AssemblerHandle.Aload(1);
    try AssemblerHandle.Operation2(0xc0, ValueClass);
    try AssemblerHandle.Invoke(0xb6, ValueMethod);
    try AssemblerHandle.Operation0(ArithmeticOpcode);
    try AssemblerHandle.Goto(BoxLabel);
}

fn EmitTypeCase(AssemblerHandle: *Assembler, Name: []const u8, TypeField: u16) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Operation2(0xb2, TypeField);
    try AssemblerHandle.Operation0(0xb0);
}
fn EmitMcPrimCase(AssemblerHandle: *Assembler, CharValue: i32, TypeField: u16, NextLabel: []const u8) !void {
    try AssemblerHandle.Iload(1);
    try AssemblerHandle.Iconst(CharValue);
    try AssemblerHandle.Branch(0xa0, NextLabel);
    try AssemblerHandle.Operation2(0xb2, TypeField);
    try AssemblerHandle.Operation0(0xb0);
    try AssemblerHandle.Label(NextLabel);
}
fn EmitArrayLoadCase(AssemblerHandle: *Assembler, Name: []const u8, GetRef: u16, ValueOfRef: u16) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Iload(1);
    try AssemblerHandle.Invoke(0xb8, GetRef);
    try AssemblerHandle.Invoke(0xb8, ValueOfRef);
    try AssemblerHandle.Operation0(0xb0);
}
fn EmitArrayStoreWide(AssemblerHandle: *Assembler, Name: []const u8, ValueClass: u16, ValueMethod: u16, SetRef: u16) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Iload(1);
    try AssemblerHandle.Aload(2);
    try AssemblerHandle.Operation2(0xc0, ValueClass);
    try AssemblerHandle.Invoke(0xb6, ValueMethod);
    try AssemblerHandle.Invoke(0xb8, SetRef);
    try AssemblerHandle.Operation0(0xb1);
}
fn EmitArrayStoreNarrow(AssemblerHandle: *Assembler, Name: []const u8, IntegerClass: u16, IntValueRef: u16, ConvertOpcode: u8, SetRef: u16) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Iload(1);
    try AssemblerHandle.Aload(2);
    try AssemblerHandle.Operation2(0xc0, IntegerClass);
    try AssemblerHandle.Invoke(0xb6, IntValueRef);
    try AssemblerHandle.Operation0(ConvertOpcode);
    try AssemblerHandle.Invoke(0xb8, SetRef);
    try AssemblerHandle.Operation0(0xb1);
}

fn CompareWideCase(AssemblerHandle: *Assembler, Name: []const u8, ValueClass: u16, ValueMethod: u16, CompareOpcode: u8, ValueOfRef: u16) !void {
    try AssemblerHandle.Label(Name);
    try AssemblerHandle.Aload(0);
    try AssemblerHandle.Operation2(0xc0, ValueClass);
    try AssemblerHandle.Invoke(0xb6, ValueMethod);
    try AssemblerHandle.Aload(1);
    try AssemblerHandle.Operation2(0xc0, ValueClass);
    try AssemblerHandle.Invoke(0xb6, ValueMethod);
    try AssemblerHandle.Operation0(CompareOpcode);
    try AssemblerHandle.Invoke(0xb8, ValueOfRef);
    try AssemblerHandle.Operation0(0xb0);
}
